FROM python:3.11

RUN mkdir -p /app

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

COPY . /app

EXPOSE 8000

CMD ["bash", "scripts/prestart.sh"]
